### ISSUE TITLE
Extend the File Type

### ISSUE THREAD

**Issue by rako999-sys** [AlexandriteSoftware/markdown-search#1]
Hi it is posible that you can extented the File Types. 

So we can also search in Powershell Files (.ps1 and .psm)

Your Search is really grate because it search for Fiel Name and File Content.

Best regards

Ralf

**Comment by alex-netkachov** [comment]
Thanks.

Do you want to search in all powershell content (variable names, etc) or
only in comments?

**Comment by rako999-sys** [comment]
In all powershell content will be nice

Thanks

**Comment by alex-netkachov** [comment]
After careful consideration and looking through alternatives I've decided that right now implementing search over other types of files in this extension does not going well along with its original purpose: full text fuzzy search in markdown-formatted knowledge bases.

There are other extensions that simplify working with PowerShell scripts, e.g. https://marketplace.visualstudio.com/search?term=powershell&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by rako999-sys** [comment]
Hi,
it's ok thank you for your efforts.

Best regards 
Ralf
